spring:
 application:
  name: digitalstore-product-service
 h2:
  console:
   enabled: true
 jackson:
  serialization:
   FAIL_ON_EMPTY_BEANS: false

server:
 port: 8888
 
eureka:
 client:
  serviceUrl:
   defaultZone: http://172.168.4.253:8761/eureka/