package com.pccw.digitalstore.brand.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

@Entity
public class Brand {
	
	@Id
	@GeneratedValue
	@ApiModelProperty(notes = "The ID of the brand, this is autogenerated")
	private Long id;
	@JsonProperty(required = true)
	@ApiModelProperty(notes = "Brand name", required = true)
	private String name;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	public String toString() {
		return "Brand [id=" + id + ", name=" + name + "]";
	}

}
